### ISSUE TITLE
Is it posssible for IE support?

### ISSUE THREAD

**Issue by andyholst** [QuantumInformation/test-recorder#1]
Hi,

Is it possible to support at least IE 11+?

Best regards

Andy

**Comment by QuantumInformation** [comment]
Should be easy, thx.

**Comment by QuantumInformation** [comment]
Is the test-recorder something that your team would find helpful?

**Comment by quantuminformation** [comment]
@MrDataAsimov due to event.path being only available for chrome, its chrome only for now I'm afraid until I figure out a suitable polyfill.
