### ISSUE TITLE
Please provide an option to keep the recorder window open between pages loading

### ISSUE THREAD

**Issue by zsardone** [QuantumInformation/test-recorder#14]
Currently when a new page is loaded the recorder window will be dismissed before user can copy the generated code. Please provide an option to keep this recorder window open until user is done recording. 

Thanks!

**Comment by quantuminformation** [comment]
WIP, good idea.

**Comment by quantuminformation** [comment]
If this option is enabled an alert could open if the user hasn't pressed copy at least once.

**Comment by quantuminformation** [comment]
Done in 0.4.1
